### ISSUE TITLE
How can I reproduce the orbit examples from the website?

### ISSUE THREAD

**Issue by gsuarezr** [chakravala/Fatou.jl#13]
How can I reproduce the orbit example 3 of the website juliafill("z^2-1",∂=[-2,2],iter=true,n=800) |> fatou |> plot
If I try that I keep getting UndefVarError: ttext not defined the website is https://crucialflow.com/Fatou.jl/

**Comment by chakravala** [comment]
Alright, I fixed it. Also, instead of `"z^2-1"` (a String) you need to use `:(z^2-1)` which is a Julia expression.

**Comment by gsuarezr** [comment]
Sorry, I probably should have said that I tried that already. I figured from the examples in the Readme 
but for example the line 

juliafill(:(z^2-1),∂=[-2,2],iter=true,n=800) |> fatou |> plot ends up with  UndefVarError: ttext not defined

however 

plot(fatou(juliafill(:(z^2-1),∂=[-2,2],iter=true,n=800)),bare=true) 

works perfectly. 

I tried using juliafill(:(z^2-1),∂=[-2,2],iter=true,n=800) |> fatou |> plot  because in the website those come with the color bar, which is something I wanted 

That sintax only fails when using juliafill, for example the line

newton(:(z^2-z-4),∂=[-4,0],n=700,cmap="RdGy",p=0.5) |> fatou |> plot

works correctly

Maybe there's another way to get the color bar for the juliafill?

**Comment by chakravala** [comment]
Yea, I fixed it already, did you try the new commit? Update to v1.1.4 of `Fatou` and see if it works.
